import type { Metadata } from "next";
import { FC, ReactNode } from 'react';

import { Footer, Header } from '../components';

import '../styles/main.css';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IRootLayout {
  children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
  return (
    <html lang="ru">
      <body className="page">
        <Header />
        <div className="zi-1 flex-grow-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
